# Generated by Django 4.0 on 2022-07-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('r_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=200)),
                ('r_email', models.CharField(max_length=200)),
                ('r_message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
