# Generated by Django 4.0.1 on 2022-07-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_adminaccount'),
        ('Home', '0002_review'),
    ]

    operations = [
    ]
