# Generated by Django 4.0.1 on 2022-07-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_merge_0002_adminaccount_0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='by',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
