# Generated by Django 4.0.1 on 2022-07-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_product_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='by',
        ),
    ]
